#!/bin/bash

USAGE="usage:
	run2 file
"
#if [ $# -eq 2 ]; then GAIN="$2"; fi
if [ $# -ne 1 ]; then echo "$USAGE"; exit -1; fi

file=$1
IFS='_' read -a strarr <<< "$file"
center=${strarr[2]}
IFS='.' read -a strarr2 <<< "${strarr[3]}"
s_rate=${strarr2[0]}

if grep -q u8 <<< $file; then
	fmt="u8"
else
	fmt="s16"
fi
echo $fmt
heat_fmt=jpg

offset=0
dec_coef=$((s_rate/48000))
rate=48000
sample_rate=$((dec_coef*rate))
echo $s_rate $dec_coef $sample_rate

if [[ !($file =~ _$sample_rate) ]]; then echo "$USAGE"; exit -1; fi

./mk_heat $1 $heat_fmt
#freqs=$(./dsd.awk -v center=$center -v sample_rate=$sample_rate ./bookmarks.csv)
freqs=$(cat freq_found)
for freq in $freqs; do
	echo $freq
	cmd="print(float($center-$freq-$offset)/$sample_rate)"
	f_shift=$(python3 -c $cmd)
	echo $f_shift
	f="$freq"_$1
	csdr convert_"$fmt"_f < $1 |csdr shift_addition_cc $f_shift|csdr fir_decimate_cc $dec_coef 0.005 HAMMING | csdr fmdemod_quadri_cf | csdr convert_f_s16 | tee /tmp/demod-$f | ./dsd -i- -fr -mc -w /tmp/$f.wav 2>/tmp/log-$f
	(sox -traw -es -L -b 16 -c 1 -r 48000 /tmp/demod-$f -t flac demod-$f.flac; rm /tmp/demod-$f) &
	(grep -q "key found" /tmp/log-$f && sox /tmp/$f.wav $f.ogg; rm /tmp/$f.wav;bzip2 -9 /tmp/log-$f;mv /tmp/log-$f.bz2 .) &
done
wait
./clean.sh
