#!/bin/bash

. rmd.cfg
. funcs.sh

WAV_SUFFIX=${WAV_SUFFIX:-".wav"}
ff=$(basename $1)

f=${ff:6:-5}
wav_pattern=/tmp/"$f"_$WAV_SUFFIX

sox $1 -traw -es -L -b 16 -c 1 -r 48000 - | ./dsd -i- -fr -mc -w $wav_pattern 2>/tmp/log-$f
(gather_result $f) &
