#!/bin/bash

ff=$(basename $1)

f=${ff:6:-5}
echo $f

sox $1 -traw -es -L -b 16 -c 1 -r 48000 - | ./dsd -i- -fr -mc -w /tmp/$f.wav 2>/tmp/log-$f
(grep -q "key found" /tmp/log-$f && sox /tmp/$f.wav $f.ogg; rm /tmp/$f.wav;bzip2 -f -9 /tmp/log-$f;mv /tmp/log-$f.bz2 .) &
